- RACK_SLOT_ID: SP-LOCAL-PROD-IE-1
## PROD IE 1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003771131004
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226058312429'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:2E:B6

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-2
## PROD IE 2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003769758404
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226058312429'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:2E:F8

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-3
## PROD IE 3
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798338103
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927212732'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:14:80

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-4
## PROD IE 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799505304
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927195457'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:13:26

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-5
## PROD IE 5
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003865920809
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226058514648'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:3E:82

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-6
## PROD IE 6
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003771265901
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226058514547'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:3E:80

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-7
## PROD IE 7
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799725001
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226058291417'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:9F:CC:14

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-8
## PROD IE 8
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003769865902
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226058284648'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:9F:CB:8C

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-9
## Anand Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003770549602
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2260583460'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:31:56

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-10
## Anand Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003770548703
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003770548703'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:31:46

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-11
## Anand Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003771128307
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003771128307'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:2F:76

##*********Gerard's boxes****************
- RACK_SLOT_ID: GERARD-GOLDENBRIDGE-PROD-IE-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003768579405
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003768579405'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:2D:D2

- RACK_SLOT_ID: GERARD-GOLDENBRIDGE-PROD-IE-2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003800609509
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003800609509'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:14:90

- RACK_SLOT_ID: GERARD-GOLDENBRIDGE-PROD-IE-3
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-004058075302
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '004058075302'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: EC:C3:02:3E:C1:2E

- RACK_SLOT_ID: GERARD-GOLDENBRIDGE-PROD-IE-4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-004058070105
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '004058075302'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: EC:C3:02:3E:C1:6C

- RACK_SLOT_ID: GERARD-GOLDENBRIDGE-PROD-IE-5
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003771131004
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2260583124'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:A6:2E:B6

- RACK_SLOT_ID: GERARD-GOLDENBRIDGE-PROD-IE-6
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798338103
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927212732'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:14:80

- RACK_SLOT_ID: SP-LOCAL-PROD-IE-3
## PROD IE 3
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799541309
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927222228'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:15:3E

- RACK_SLOT_ID: RAJARAM-LOCAL-PROD-IE-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300022004505
  PLATFORM: APOLLO
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33002
  RED_RAT_IR_DEVICE: 'RedRat-X 24003'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300022004505'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:99:C5

- RACK_SLOT_ID: ECX-LOCAL-PROD-HYBRID-IE-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-004044973404
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33002
  RED_RAT_IR_DEVICE: 'RedRat-X 24003'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '004044973404'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:99:C5 

- RACK_SLOT_ID: RAJARAM-LOCAL-PROD-IE-2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-004118686007
  PLATFORM: APOLLO
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33002
  RED_RAT_IR_DEVICE: 'RedRat-X 24003'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '004118686007'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 6C:4B:B4:CE:AB:6C