- RACK_SLOT_ID: SP-RACK-SLOT-1
## PROD UK 2 with HDD 52%  Issue Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799436807
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927167676'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:10:FA


- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-1
## PROD UK 1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798601906
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927197881'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:13:56

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-2
## PROD UK 2     Issue Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003771457508
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225926130416'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: OC:O8:B4:95:47:9A


##Test Box from UK
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-3
## PROD UK 2 with HDD 52%  Issue Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798636605
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927146182'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:4C


##Kamal Box in place
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003436383909
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218473253046'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 34:38:B7:55:4B:4A

##Issue Box
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-5
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798602508
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927224753'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:15:70

##Issue Box
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-6
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799527407
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927145071'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:36

#Kamal Box
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-7
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798153700
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927141132'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0E:E8

#Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-8
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003800547402
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927153658'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:E2

#Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-9
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003800611604
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927161717'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:10:84

#Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-10
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799517507
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927151335'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:B4

 #Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-15
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798095703
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927157799'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:10:34

 #Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-11
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798632505
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927154971'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:FC

 #Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-12
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798647107
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927160606'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:10:6E

  #Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-13
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003798099101
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225927162020'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:10:8A

  #Country Rack
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-UK-14
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003799774108
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2259272235'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:15:58

### PAUL's BOXES
- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003800475406
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '200602648'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:15:6A


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003799426303
  PLATFORM: EOS1008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '200283020'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:1C


#Martin Finn Box
- RACK_SLOT_ID: MARTIN-RACK-SLOT-PROD-UK-01
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOSSTB-003906165505
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '226059736776'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:C7:8B:D0


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-3
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 3C36E4-EOSSTB-003379333903
  PLATFORM: DCX960-D
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3379333903'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:DA:F9:51:CF:6D


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 3C36E4-EOSSTB-003625804806
  PLATFORM: DCX960-D
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3625804806'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 50:95:51:7E:B2:52


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-5
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003798635904
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3798635904'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:D2


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-6
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003799783000
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3799783000'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: E8:B2:FE:9F:CC:3C


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-7
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003798635904
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3798635904'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0F:D3


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-8
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 3C36E4-EOSSTB-003583073501
  PLATFORM: DCX960-D
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3583073501'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: C0:A0:0D:AA:B9:DF


- RACK_SLOT_ID: PAUL-RACK-SLOT-PROD-UK-9
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003798153700
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3798153700'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 0C:08:B4:FA:0E:E8

- RACK_SLOT_ID: BENTO-RACK-SLOT-PROD-UK-04
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: E0B7B1-APLSTB-300017791603
  PLATFORM: EOS1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300017791603'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 6C:A6:04:8E:D8:40

- RACK_SLOT_ID: BENTO-RACK-SLOT-PROD-UK-05
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: E0B7B1-APLSTB-300023395605
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300023395605'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:94:E2

- RACK_SLOT_ID: BENTO-RACK-SLOT-PROD-UK-06
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: E0B7B1-APLSTB-300017779202
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300017779202'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 6C:A6:04:8E:DD:44

- RACK_SLOT_ID: EOS-HUMAX-RACK-SLOT-PROD-HYBRID-UK-01
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003800547402
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003800547402'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 6C:A6:04:8E:DD:44

- RACK_SLOT_ID: EOS-HUMAX-RACK-SLOT-PROD-HYBRID-UK-02
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOSSTB-003800611604
  PLATFORM: EOS-1008R
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003800611604'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 6C:A6:04:8E:DD:44