- RACK_SLOT_ID: YUKA-LOCAL-PROD-PL-1
## PROD NL LOCAL
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300027624307
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300027624307'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:79:8A:6E

- RACK_SLOT_ID: PRDP-DESK-PROD-PL-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300027627706
  PLATFORM: APOLLO
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300027627706'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:95:C3

- RACK_SLOT_ID: BANU-DESK-PROD-PL-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300010009201
  PLATFORM: APOLLO
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300010009201'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:79:87:F5

- RACK_SLOT_ID: YUKA-LOCAL-PROD-PL-2
## PROD NL LOCAL
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300010010506
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300010010506'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:79:8A:6E

- RACK_SLOT_ID: PRDP-DESK-PROD-PL-2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300027627300
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300027627300'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:95:C3


- RACK_SLOT_ID: PERF-TEST-PROD-PL-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID:  E0B7B1-APLSTB-300027222300
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300027222300'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:96:B7

- RACK_SLOT_ID: PERF-TEST-PROD-PL-2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: E0B7B1-APLSTB-300027221500
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '300027221500'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:99:C5
