- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-1
## PROD BE 1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003691451805
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218304723658'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:EC:BC

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-2
## PROD BE 2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003687302608
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218304703959'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:D8:C7

- RACK_SLOT_ID: E2ESI-RACK-SLOT-PROD-BE-1
## PROD BE 2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003661770101
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225764813134'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:FF:19

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-3
## PROD BE 3
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003661770101
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225764813134'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:FF:19

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003687984801
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218304723759'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:EC:DF

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-5
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003679819106
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225764701328'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:EB:8C

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-6
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003668221801
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225764692943'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:44:EC:87

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-7
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003691096808
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225764928195'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:F5:32:45:0E:65

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-8
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003673898403
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225824985370'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:2D:C0:7C:13:DC

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-9
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003696159601
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225824865257'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 34:1F:E4:DC:2F:23

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-10
#Yuka's box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003479671806
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218237784364'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 90:9D:7D:2F:BA:ED


- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-11
#Yuka's box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003380879803
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218150798298'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 34:1F:E4:A5:B3:07


- RACK_SLOT_ID: SP-RACK-SLOT-PROD-BE-12
#Sanity Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003496791009
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003496791009'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 90:9D:7D:70:C2:46

- RACK_SLOT_ID: RR-LOCAL-PROD-BE-1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOS2STB-008389029300
  PLATFORM: EOS2008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False
  PANORAMIX_SUPPORT: False
  CA_ID: '226208925556'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 00:00:00:00:00:00

- RACK_SLOT_ID: RR-LOCAL-PROD-BE-2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 000378-EOS2STB-008389083109
  PLATFORM: EOS2008C
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False
  PANORAMIX_SUPPORT: False
  CA_ID: '226208926061'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 00:00:00:00:00:00

- RACK_SLOT_ID: RR-LOCAL-PROD-BE-3
#Sanity Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003479671806
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218237784364'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 90:9D:7D:2F:BA:ED

- RACK_SLOT_ID: RR-LOCAL-PROD-BE-4
#Sanity Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003398475602
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218188878490'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 34:1F:E4:A5:B1:E9

