- RACK_SLOT_ID: FCOBOS-RACK-SLOT-PROD-NL-1
## PROD NL 1
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003637806807
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218495274252'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA

- RACK_SLOT_ID: VISHWA-RACK-SLOT-PROD-NL-1
## PROD NL 2
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003497745301
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218495274252'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 50:95:51:C4:27:05
  
- RACK_SLOT_ID: VISHWA-RACK-SLOT-PROD-NL-2
## PROD NL 3
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003497766307
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218495274252'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 50:95:51:C4:27:05

- RACK_SLOT_ID: SP-LOCAL-PROD-NL-1
## PROD NL 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003493932200
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218296702224'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: BC:2E:48:92:79:3F

- RACK_SLOT_ID: SP-LOCAL-PROD-NL-2
## PROD NL 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003498785207
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017698621'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: BC:2E:48:92:7D:CC

- RACK_SLOT_ID: SP-LOCAL-PROD-NL-3
## PROD NL 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003493932309
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017698622'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: BC:2E:48:92:7A:E3

- RACK_SLOT_ID: SP-LOCAL-PROD-NL-4
## PROD NL 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003685570909
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218296702224'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: BC:2E:48:92:7A:E3

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-2
## PREPROD NL 2   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003674148709
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '225788343646'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:2D:C0:2A:8F:6B

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-3
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003616292706
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017695350'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:E0:E0:7A

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-4
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003597937907
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017695797'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:E0:E7:70

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-5
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003453288601
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017695767'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:E0:DF:C9

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-6
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003591157205
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017695772'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:9A:24:2B

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-7
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003600730000
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017695780'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:E1:27:21

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-8
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003639017304
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017697111'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 50:95:51:C3:42:7C

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-9
## PREPROD NL 3   PRD Build
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003493932309
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218296709698'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: BC:2E:48:92:7A:E3

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-10
## PREPROD NL 3   PRD Build Subbu box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003692155405
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017728189'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:2D:C0:2A:9D:66

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-11
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-179595594150
  PLATFORM: SMT-G7400
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33002
  RED_RAT_IR_DEVICE: 'RedRat-X 24001'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '179595594150'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11


- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-12
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-218127354563
  PLATFORM: SMTG7401
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0018023640'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-13
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-218025920624
  PLATFORM: SMT-G7401
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33001
  RED_RAT_IR_DEVICE: 'RedRat-X 24003'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0018105465'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-14
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-179596607391
  PLATFORM: SMTG7400
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33002
  RED_RAT_IR_DEVICE: 'RedRat-X 24001'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0018107871'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-15
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-171588654458
  PLATFORM: SMTG7400
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0018107874'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11

- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-16
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-218079813234
  PLATFORM: SMTG7401
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0018023634'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11

#Raymon's boxes
- RACK_SLOT_ID: SP-RACK-SLOT-PROD-NL-17
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 0000F0-HZNSTB-218476104648
  PLATFORM: SMTG7401
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '218476104648'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 20:D5:BF:B6:DA:11

#SP's boxes
- RACK_SLOT_ID: KHU-RACK-SLOT-PROD-NL-18
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: 3C36E4-EOSSTB-003483170001
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003483170001'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 90:9D:7D:70:B7:EE

- RACK_SLOT_ID: SP-LOCAL-PROD-NL-5
## PROD NL 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003490693201
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 33001
  RED_RAT_IR_DEVICE: 'RedRat-X 24001'
  RED_RAT_DEVICE_OUTPUT_PORT: 4
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '0017695285'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: BC:2E:48:92:72:6F

- RACK_SLOT_ID: SP-LOCAL-PROD-NL-6
## PROD NL 4
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003674364603
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003674364603'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: F8:2D:C0:29:4C:9C

- RACK_SLOT_ID: SB-RACK-SLOT-PROD-NL-01
## Shiba's Box
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 0000F0-HZNSTB-179848333339
  PLATFORM: SMT-G7400
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '179848333339'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 54:FA:3E:15:A1:6E

- RACK_SLOT_ID: ECX-RACK-SLOT-PROD-NL-01
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003674364603
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2262042045'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: C8:52:61:C8:0B:18

- RACK_SLOT_ID: KAB-RACK-SLOT-PROD-NL-01
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003453288601
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2184610940'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:E0:DF:C9

- RACK_SLOT_ID: KAB-RACK-SLOT-PROD-NL-02
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003616292706
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '003616292706'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: 2C:95:69:E0:E0:7A

- RACK_SLOT_ID: KAB-RACK-SLOT-PROD-NL-03
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOS2STB-008389544803
  PLATFORM: 2008C-STB-PROD
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2262492100'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: EC:C3:02:36:77:C4

- RACK_SLOT_ID: KAB-RACK-SLOT-PROD-NL-04
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOS2STB-008391778605
  PLATFORM: 2008C-STB-PROD
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2262492100'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: EC:C3:02:36:77:C4

- RACK_SLOT_ID: NL-RACK-PROD-NL-APOLLO-01
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: E0B7B1-APLSTB-300015574506
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3000155745'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:97:60

- RACK_SLOT_ID: NL-RACK-PROD-NL-APOLLO-02
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1
  ROUTER_PC_IP: 127.0.0.1
  CPE_ID: E0B7B1-APLSTB-300023782505
  PLATFORM: VIP5002W-PRD
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '3000155745'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: B0:83:D6:FB:97:60

- RACK_SLOT_ID: KAB-RACK-SLOT-PROD-NL-05
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 000378-EOS2STB-008391771501
  PLATFORM: 2008C-STB-PROD
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2262492100'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: EC:C3:02:36:77:C4

- RACK_SLOT_ID: ECX-RACK-PROD-NL-EOS-03
  PDU_IP: 127.0.0.1
  RACK_PC_IP: 127.0.0.1   #10.65.55.21
  ROUTER_PC_IP: 127.0.0.1 #10.64.200.200
  CPE_ID: 3C36E4-EOSSTB-003490693201
  PLATFORM: DCX960
  RED_RAT_IR_IP: 127.0.0.1
  RED_RAT_IR_PORT: 00000
  RED_RAT_IR_DEVICE: 'RedRat-X 24000'
  RED_RAT_DEVICE_OUTPUT_PORT: 1
  LAN_PC_IP: 127.0.0.1
  TEST_STATUS: NA
  OBELIX_SUPPORT: False #True
  PANORAMIX_SUPPORT: False
  CA_ID: '2262042045'
  RL_PORT: 0000
  PDU_TYPE: REST
  RACK_TYPE: NA
  STB_MAC: C8:52:61:C8:0B:18
