APP_1: Vimeo
APP_2: Virtuagym
APP_Netflix: Netflix
APP_Youtube: YouTube
CHANNEL_ZAP_HD_CHANNEL: '5'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '115'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '998'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '1'
CHANNEL_ZAP_SD_CHANNEL: '211'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '5'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2: '2'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '809'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '101'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '98'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '10'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'False'
PRODUCT: APOLLO
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 81
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: The Big Bang Theory
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Dowód
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: Teoria wielkiego podrywu S12, Ep17 - Konferencyjna
  wycena
SAVED_RENTED_ASSET: Mulan
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: '607'
SAVED_SINGLE_EVENT_CHANNEL: '247'
SAVED_WATCHLIST_ASSET: Mulan
SAVED_WATCHLIST_LABEL: WATCHLIST
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- TVN_Fabula_HD
- Polsat_Food_HD
- Travel_Channel_HD
- TLA_5_DAWN
- Metro_HD
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- TVP_1_HD
- TVP_2_HD
- TVN_HD
- TVP_Seriale
- AXN_White
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: Comedy_Central_HD_dubel
STARTUP_COLDSTANDBY_DELAY_SECONDS: 1800
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
TV_GUIDE_CARTOON_CHANNEL: 601
TV_GUIDE_REPLAY_ASSET: Mów mi Dave
TV_GUIDE_REPLAY_CHANNEL: '205'
VOD_CATEGORIES_ASSET: '300: Rise of an Empire'
VOD_CATEGORIES_COLLECTION: Action & Adventure
VOD_CATEGORIES_LABEL: MYPRIME
VOD_CATEGORY_ASSET: A Minuscule Adventure
VOD_CATEGORY_COLLECTION: All
VOD_DISCOVER_ASSET: Małe Szczęścia
VOD_DISCOVER_COLLECTION: Ostatnio dodane
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: 'Między nami, misiami: Film'
VOD_KIDS_COLLECTION: Cartoon Network
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: Pułapka
VOD_MOVIES_COLLECTION: TVN
VOD_MOVIES_LABEL: MYPRIME
VOD_PROVIDERS_ASSET: UCIECZKA NA WIEŚ 19
VOD_PROVIDERS_COLLECTION: Nowości
VOD_PROVIDERS_LABEL: CHANNELS
VOD_PROVIDERS_PROVIDER: DOMO+
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_PROVIDERS_PROVIDER_SECTION: ''
VOD_RENT_LABEL: RENTAL
VOD_SERIES_ASSET: U SĄSIADÓW W KUCHNI 10
VOD_SERIES_COLLECTION: New Series
VOD_SERIES_LABEL: SERIES