XAP_TIMEOUT: 'False'
PERF_CHECK_XAP_TIMEDOUT: 'False'
APP_1: Prime Video
APP_2: BBC iPlayer
APP_Netflix: Netflix
APP_Youtube: YouTube
CHANNEL_APP_1: '204'
CHANNEL_APP_2: '205'
CHANNEL_ZAP_HD_CHANNEL: '168'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '103'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '202'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '104'
CHANNEL_ZAP_SD_CHANNEL: '103'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '117'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '704'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '103'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2: '105'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '103'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '168'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '-1'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '-1'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'True'
PRODUCT: BENTO
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 144
SAVED_CONTINUE_WATCHING_LABEL: Continue Watching
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: Friends
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Heno
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: Friends S10, Ep1 - The One After Joey & Rachel Kiss
SAVED_RENTED_ASSET: Happy Halloween, Scooby-Doo!
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: '168'
SAVED_SINGLE_EVENT_CHANNEL: 403
SAVED_WATCHLIST_ASSET: Happy Halloween, Scooby-Doo!
SAVED_WATCHLIST_LABEL: WATCHLIST
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- '103'
- '352'
- '1960'
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- '1549'
- '1548'
- '1406'
- '1397'
- '232'
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: '1497'
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
TV_GUIDE_CARTOON_CHANNEL: '168'
TV_GUIDE_REPLAY_ASSET: Heini, Deinosoriad
TV_GUIDE_REPLAY_CHANNEL: '211'
VOD_CATEGORIES_LABEL: CATEGORIES
VOD_CATEGORY_ASSET: Alien Parasite
VOD_CATEGORY_COLLECTION: Sci-Fi & Fantasy
VOD_DISCOVER_ASSET: 'The Jinx: The Life and Deaths of Robert Durst'
VOD_DISCOVER_COLLECTION: Recommended for You
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: Rainbow Butterfly Unicorn Kitty
VOD_KIDS_COLLECTION: Kids
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: Bull
VOD_MOVIES_COLLECTION: SKY CINEMA • Premieres
VOD_MOVIES_LABEL: MOVIES
VOD_PROVIDERS_ASSET: Angry Birds
VOD_PROVIDERS_COLLECTION: ''
VOD_PROVIDERS_LABEL: CHANNELS
VOD_PROVIDERS_PROVIDER: Virgin TV Kids
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_RENT_LABEL: STORE
VOD_SERIES_ASSET: Stateside Sitcoms
VOD_SERIES_COLLECTION: Nathan for You
VOD_SERIES_LABEL: BOX SETS
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS