APP_1: Videoland
APP_2: Film1
APP_Netflix: Netflix
APP_Youtube: YouTube
CHANNEL_ZAP_HD_CHANNEL: '111'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '4'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '998'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '1'
CHANNEL_ZAP_SD_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '111'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '997'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '101'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '77'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '10'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'False'
PRODUCT: SELENE
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 28
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: Idioten op de weg
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Paw Patrol
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: Idioten op de weg S5, Ep19
SAVED_RENTED_ASSET: 'Jumanji: The Next Level'
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: 15
SAVED_SINGLE_EVENT_CHANNEL: 13
SAVED_WATCHLIST_ASSET: 'Jumanji: The Next Level'
SAVED_WATCHLIST_LABEL: WATCHLIST
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- TVN_Fabula_HD_dubel
- Polsat_Food_HD_dubel
- Travel_Channel_dubel
- TLA_5_DAWN
- Metro_HD_Dubel
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- TVP_1_HD
- TVP_2_HD
- TVN_HD
- TVP_Seriale
- AXN_White
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: TVP_1_HD
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
STARTUP_COLDSTANDBY_DELAY_SECONDS: 1800
TV_GUIDE_CARTOON_CHANNEL: 307
TV_GUIDE_REPLAY_ASSET: Paw Patrol S5, Pups redden de Reddingskatten Club / Pups redden
  een struisvogel
TV_GUIDE_REPLAY_CHANNEL: '306'
VOD_DISCOVER_ASSET: Dora the Explorer
VOD_DISCOVER_COLLECTION: Popular for kids
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: 'Gabby Duran: De Alien Babysitter'
VOD_KIDS_COLLECTION: Last chance
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: 'Hans Teeuwen: Echte Rancune'
VOD_MOVIES_COLLECTION: Last chance
VOD_MOVIES_LABEL: MOVIES
VOD_PROVIDERS_ASSET: Buried
VOD_PROVIDERS_COLLECTION: Last chance
VOD_PROVIDERS_LABEL: PROVIDERS
VOD_PROVIDERS_PROVIDER: Film1
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_PROVIDERS_PROVIDER_SECTION: ''
VOD_RENT_LABEL: RENT
VOD_SERIES_ASSET: Bia
VOD_SERIES_COLLECTION: Last chance
VOD_SERIES_LABEL: SERIES
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS