XAP_TIMEOUT: 'False'
PERF_CHECK_XAP_TIMEDOUT: 'False'
APP_1: Sky Show
APP_2: Stingray Music
APP_Netflix: Sky Show
APP_Youtube: YouTube
CHANNEL_APP_1: '149'
CHANNEL_APP_2: '99'
CHANNEL_ZAP_HD_CHANNEL: '12'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '4'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '998'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '1'
CHANNEL_ZAP_SD_CHANNEL: '40'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '15'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2: '204'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '999'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '101'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '91'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '10'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'False'
PRODUCT: EOS
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 12
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: Meine Vorfahren
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Yamashitas Gold - Der Fluch des Pazifiks
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: Meine Vorfahren S1, Ep3
SAVED_RENTED_ASSET: Tenet
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: '46'
SAVED_SINGLE_EVENT_CHANNEL: '538'
SAVED_WATCHLIST_ASSET: Tenet
SAVED_WATCHLIST_LABEL: WATCHLIST
PHS_RAIL_WATCHLIST_ID: 'coPe_3e4f6fdb-ad51-40a8-9db8-9a896dafe270~omw_basic~en'
PHS_RAIL_CONTINUE_WATCHING_ID : 'coCo_92c70409-3c79-496a-b701-c658d5156931~omw_basic~en'
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- SV06525
- SV00039
- SV06077
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- SV09038
- SV09039
- SV09006
- SV09036
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: SV09036
STARTUP_COLDSTANDBY_DELAY_SECONDS: 360
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
STARTUP_LUKEWARMSTANDBY_DELAY_SECONDS: 360
TV_GUIDE_CARTOON_CHANNEL: 331
TV_GUIDE_REPLAY_ASSET: Planet Wissen, Intelligente Pflanzen - Quick lebendig und ganz
  schön raffiniert
TV_GUIDE_REPLAY_CHANNEL: '172'
VOD_DISCOVER_ASSET: 10. Mai, Der
VOD_DISCOVER_COLLECTION: Filmo - Schweizer Filme
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: Willkommen im Wunder Park
VOD_KIDS_COLLECTION: Favourite Animated Movies
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: Fear of Rain - Die Angst in Dir
VOD_MOVIES_COLLECTION: Favourite Horror Movies
VOD_MOVIES_LABEL: MOVIES
VOD_PROVIDERS_ASSET: Buffalo '66
VOD_PROVIDERS_COLLECTION: Comedy & Romance Movies
VOD_PROVIDERS_LABEL: LIONSGATE+
VOD_PROVIDERS_PROVIDER: ''
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_PROVIDERS_PROVIDER_SECTION: ''
VOD_RENT_LABEL: MOVIES
VOD_SERIES_ASSET: Lehrer, Die
VOD_SERIES_COLLECTION: Swiss Made
VOD_SERIES_LABEL: SERIES
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS