APP_1: TV Shop
APP_2: Netflix
APP_Netflix: Netflix
APP_Youtube: YouTube
CHANNEL_APP_1: '600'
CHANNEL_APP_2: '600'
CHANNEL_ZAP_HD_CHANNEL: '12'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '4'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '998'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '1'
CHANNEL_ZAP_SD_CHANNEL: '10'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '15'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2 : '204'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '813'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '100'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '91'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '10'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'False'
PRODUCT: EOSV2
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 12
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: Der Prinz von Bel-Air
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Cantando e ballando
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: Der Prinz von Bel-Air S6, Ep1 - Flambierte Bananen
SAVED_RENTED_ASSET: 'Paranormal Activity 4'
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: '12'
SAVED_SINGLE_EVENT_CHANNEL: '38'
SAVED_WATCHLIST_ASSET: 'Platzspitzbaby'
SAVED_WATCHLIST_LABEL: WATCHLIST
PHS_RAIL_WATCHLIST_ID: 'coPe_2a5d5105-41d1-4de9-b940-0e6ece7397ff~omw_playmore~en'
PHS_RAIL_CONTINUE_WATCHING_ID : 'coCo_a1f4c2dd-f405-4ec7-9b9e-6a7670c2501c~omw_playmore~en'
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- c8
- tmc
- tfx
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- vtmhd
- eenhd
- kanaalz
- ketnet
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: ketnet
STARTUP_COLDSTANDBY_DELAY_SECONDS: 360
STARTUP_LUKEWARMSTANDBY_DELAY_SECONDS: 360
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
TV_GUIDE_CARTOON_CHANNEL: 43
TV_GUIDE_REPLAY_ASSET: We Bare Bears, Tunnels
TV_GUIDE_REPLAY_CHANNEL: '10'
VOD_DISCOVER_ASSET: 'Men in Black'
VOD_DISCOVER_COLLECTION: Feel Good Movies
VOD_DISCOVER_LABEL: ONTDEK
VOD_KIDS_ASSET: Penguins of Madagascar (NL)
VOD_KIDS_COLLECTION: Last chance
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: Gek van Geluk
VOD_MOVIES_COLLECTION: Last chance
VOD_MOVIES_LABEL: FILMS
VOD_PROVIDERS_ASSET: Mad men
VOD_PROVIDERS_COLLECTION: ''
VOD_PROVIDERS_LABEL: ZENDERS
VOD_PROVIDERS_PROVIDER: ''
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_PROVIDERS_PROVIDER_SECTION: VTM
VOD_RENT_LABEL: FILMS
VOD_SERIES_ASSET: Saving Hope
VOD_SERIES_COLLECTION: All
VOD_SERIES_LABEL: SERIES
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS