XAP_TIMEOUT: 'False'
PERF_CHECK_XAP_TIMEDOUT: 'False'
APP_1: Videoland
APP_2: ' XITE Music Videos'
APP_Netflix: 'XITE | music videos'
APP_Youtube: YouTube
CHANNEL_APP_1: '150'
CHANNEL_APP_2: '151'
CHANNEL_ZAP_HD_CHANNEL: '15'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '4'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '998'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '1'
CHANNEL_ZAP_SD_CHANNEL: '309'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '15'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2 : '204'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '997'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '101'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '77'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '10'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'False'
PRODUCT: EOSV2
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 28
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: New Girl
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Teen Titans Go!
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: New Girl S6, Ep8 - James Wonder
SAVED_RENTED_ASSET: 'Jumanji: Welcome to the Jungle'
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: '202'
SAVED_SINGLE_EVENT_CHANNEL: '20'
SAVED_WATCHLIST_ASSET: 'Jumanji: Welcome to the Jungle'
SAVED_WATCHLIST_LABEL: WATCHLIST
PHS_RAIL_WATCHLIST_ID: 'coPe_24cab291-d7f9-4640-942d-f285f8ab3251~omw_playmore~en'
PHS_RAIL_CONTINUE_WATCHING_ID : 'coCo_91770cd2-9f6b-4518-82fa-a804a73e40a8~omw_playmore~en'
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- NL_000001_019401
- NL_000004_019461
- NL_000038_019063
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- NL_000088_019251
- NL_000077_019706
- NL_000015_019166
- NL_000090_019492
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: NL_000021_019566
STARTUP_COLDSTANDBY_DELAY_SECONDS: 360
STARTUP_LUKEWARMSTANDBY_DELAY_SECONDS: 360
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
TV_GUIDE_CARTOON_CHANNEL: 307
TV_GUIDE_REPLAY_ASSET: We Bare Bears, Tunnels
TV_GUIDE_REPLAY_CHANNEL: '307'
VOD_DISCOVER_ASSET: 'Captain Underpants: The First Epic Movie (NL)'
VOD_DISCOVER_COLLECTION: Popular for kids
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: Penguins of Madagascar (NL)
VOD_KIDS_COLLECTION: Last chance
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: Gek van Geluk
VOD_MOVIES_COLLECTION: Last chance
VOD_MOVIES_LABEL: MOVIES
VOD_PROVIDERS_ASSET: The Hitman's Bodyguard
VOD_PROVIDERS_COLLECTION: Last chance
VOD_PROVIDERS_LABEL: PROVIDERS
VOD_PROVIDERS_PROVIDER: Film1
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_RENT_LABEL: RENT
VOD_SERIES_ASSET: Saving Hope
VOD_SERIES_COLLECTION: All
VOD_SERIES_LABEL: SERIES
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS
VOD_PROVIDERS_PROVIDER_SECTION: ''