XAP_TIMEOUT: 'False'
PERF_CHECK_XAP_TIMEDOUT: 'False'
APP_1: prime video
APP_2: BBC iPlayer
APP_Netflix: BBC iPlayer
APP_Youtube: YouTube
CHANNEL_APP_1: '204'
CHANNEL_APP_2: '205'
CHANNEL_ZAP_HD_CHANNEL: '132'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '105'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '601'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '209'
CHANNEL_ZAP_SD_CHANNEL: '121'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '-1'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '-1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '108'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2: '109'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '266'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '401'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '-1'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '-1'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'True'
PRODUCT: EOS
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 128
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: Everybody Loves Raymond
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Combat Dealers
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: Everybody Loves Raymond S7, Ep20 - Who's Next
SAVED_RENTED_ASSET: 'Tom & Jerry: The Movie'
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: 132
SAVED_SINGLE_EVENT_CHANNEL: 403
SAVED_WATCHLIST_ASSET: 'Tom & Jerry: The Movie'
SAVED_WATCHLIST_LABEL: WATCHLIST
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- '103'
- '352'
- '1960'
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- '1549'
- '1548'
- '1406'
- '1397'
- '232'
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_MIN_RECORDING_LEVEL: 10
SETUP_SAVED_SERIES_CHANNEL: '1497'
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
TV_GUIDE_CARTOON_CHANNEL: '704'
TV_GUIDE_REPLAY_ASSET: How It's Made S2, Ep13
TV_GUIDE_REPLAY_CHANNEL: '169'
VOD_CATEGORIES_LABEL: CATEGORIES
VOD_CATEGORY_ASSET: Alien Parasite
VOD_CATEGORY_COLLECTION: Sci-Fi & Fantasy
VOD_DISCOVER_ASSET: Cruise Ship Killers
VOD_DISCOVER_COLLECTION: True Crime
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: Virgin TV Kids
VOD_KIDS_COLLECTION: Channels
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: 'Tom & Jerry: The Movie'
VOD_MOVIES_COLLECTION: STORE • New movies to buy or rent
VOD_MOVIES_LABEL: MOVIES
VOD_PROVIDERS_ASSET: Angry Birds
VOD_PROVIDERS_COLLECTION: ''
VOD_PROVIDERS_LABEL: CHANNELS
VOD_PROVIDERS_PROVIDER: Virgin TV Kids
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_RENT_LABEL: STORE
VOD_SERIES_ASSET: 'Power Book II: Ghost'
VOD_SERIES_COLLECTION: STARZPLAY - US Drama
VOD_SERIES_LABEL: BOX SETS
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS
VOD_PROVIDERS_PROVIDER_SECTION: ''