XAP_TIMEOUT: 'False'
PERF_CHECK_XAP_TIMEDOUT: 'False'
APP_1: Tetris
APP_2: Vimeo
APP_Netflix: Netflix
APP_Youtube: YouTube
CHANNEL_APP_1: '300'
CHANNEL_ZAP_HD_CHANNEL: '104'
CHANNEL_ZAP_NonScrambled_HD_CHANNEL: '214'
CHANNEL_ZAP_QAM_FINAL_CHANNEL: '809'
CHANNEL_ZAP_QAM_INIT_CHANNEL: '100'
CHANNEL_ZAP_SD_CHANNEL: '342'
CHANNEL_ZAP_SINGLE_DIGIT_FINAL_CHANNEL: '9'
CHANNEL_ZAP_SINGLE_DIGIT_INIT_CHANNEL: '1'
CHANNEL_ZAP_Scrambled_HD_CHANNEL: '115'
CHANNEL_ZAP_Scrambled_HD_CHANNEL_2 : '304'
CHANNEL_ZAP_THREE_DIGIT_FINAL_CHANNEL: '809'
CHANNEL_ZAP_THREE_DIGIT_INIT_CHANNEL: '101'
CHANNEL_ZAP_TWO_DIGIT_FINAL_CHANNEL: '77'
CHANNEL_ZAP_TWO_DIGIT_INIT_CHANNEL: '10'
DEFAULT_RETRY_INTERVAL: 0ms
DEFAULT_RETRY_TIMEOUT: 10s
GFX_RESOLUTION: 720
LDVR_ENABLED: 'True'
PRODUCT: EOS
REVIEW_BUFFER_TRICKPLAY_CHANNEL: 727
SAVED_CONTINUE_WATCHING_LABEL: CONTINUE WATCHING
SAVED_CONTINUE_WATCHING_RECORDING_ASSET: Back to the Future
SAVED_CONTINUE_WATCHING_REPLAY_ASSET: Teleshopping
SAVED_RECORDINGS_LABEL: RECORDINGS
SAVED_RECORDINGS_SERIES_ASSET: We Bare Bears
SAVED_RENTED_ASSET: We Bare Bears
SAVED_RENTED_LABEL: RENTED
SAVED_SERIES_CHANNEL: 166
SAVED_SINGLE_EVENT_CHANNEL: 160
SAVED_WATCHLIST_ASSET: Harry Potter And The Deathly Hallows-Part 2
SAVED_WATCHLIST_LABEL: WATCHLIST
SEARCH_CHAR_1: Y
SEARCH_CHAR_2: Yo
SEARCH_CHAR_3: You
SETUP_LTV_ZAP_NONSCRAMBLED_CHANNELS:
- IESVC1076
- IESVC1077
- IESVC1172
- IESVC1225
- IESVC1227
- IESVC1228
SETUP_LTV_ZAP_SCRAMBLED_CHANNELS:
- IESVC1232
- IESVC1085
- IESVC1043
- IESVC1273
- IESVC1166
- IESVC1183
- IESVC1267
- IESVC1288
SETUP_MIN_BOOKINGS_SERIES: 3
SETUP_MIN_BOOKINGS_SINGLE: 2
SETUP_SAVED_SERIES_CHANNEL: IESVC1240
STARTUP_HOTSTANDBY_DELAY_SECONDS: 60
TV_GUIDE_CARTOON_CHANNEL: 104
TV_GUIDE_REPLAY_ASSET: Clarence S1, Ep2 - A Pretty Great Day With a Girl
TV_GUIDE_REPLAY_CHANNEL: '104'
VOD_DISCOVER_ASSET: The Chase
VOD_DISCOVER_COLLECTION: VIRGIN MEDIA PLAYER
VOD_DISCOVER_LABEL: DISCOVER
VOD_KIDS_ASSET: 101 Dalmatians
VOD_KIDS_COLLECTION: POPULAR MOVIES
VOD_KIDS_LABEL: KIDS
VOD_MOVIES_ASSET: 101 Dalmatians
VOD_MOVIES_COLLECTION: VIRGIN MOVIES - All
VOD_MOVIES_LABEL: VIRGIN MOVIES
VOD_PROVIDERS_ASSET: Taffy
VOD_PROVIDERS_COLLECTION: SKY ARTS MUSIC
VOD_PROVIDERS_LABEL: CATCH UP
VOD_PROVIDERS_PROVIDER: ''
VOD_PROVIDERS_PROVIDER_COLLECTION: ''
VOD_PROVIDERS_PROVIDER_SECTION: ''
VOD_RENT_LABEL: RENT
VOD_SERIES_ASSET: Ant and Dec's Saturd
VOD_SERIES_COLLECTION: MOST POPULAR
VOD_SERIES_LABEL: BOXSETS
VOD_SHOWS_ASSET: Curse of Oak Island, The
VOD_SHOWS_COLLECTION: Last chance
VOD_SHOWS_LABEL: SHOWS
VOD_SKYCINEMA_ASSET: NFL Overtime 22.09
VOD_SKYCINEMA_COLLECTION: SKY SPORTS HD
VOD_SKYCINEMA_COLLECTION_HEADING: SKY CINEMA • SKY CINEMA - All
VOD_SKYCINEMA_LABEL: SKY CINEMA & SPORTS