#!/usr/bin/env python

INITIAL_TESTCASE = "STEP_HES/NAV/HES_NAV.json::HES_RESET CPE UI WITHOUT CHECKS - BACK-BACK-BACK"
E2E_CONF = {
    "tedh_qa_pre_nl": {
        "CPE_FW_VERSION": "060-ap",
        # "CPE_ID": "3C36E4-EOSSTB-003674367101",
        "country": "nl",
        "default_language": "en",
        "root_id": ["omw_playmore_en"],
        "fallback_root_id": ["omw_hzn4_vod"],
        "ITFAKER": {"host": "itfaker.preprod.nl.internal", "port": 80, "env": "vodziggopreprod"},
        "VRM": {"BS": {"host": "vrm_bs_8092.preprod.nl.internal", "ports": [80]},
                "DS": {"host": "vrm_ds_8083.preprod.nl.internal", "ports": [80]},
                "BS1": {"host": "vrm_bs_8092.preprod.nl.internal", "ports": [80]},
                "BS2": {"host": "vrm_bs_8092.preprod.nl.internal", "ports": [80]}
        },
        # BLOCKED
        "SEACHANGE": {"TRAXIS_WEB": {"host": "obotraxis.preprod.nl.internal", "port": 80, "path": "traxis/web"}},
        # BLOCKED
        "MICROSERVICES": {
            "OBOQBR": "oboqbr.preprod.nl.internal"
        },
        "XAP": {"host": "xap.pre-nl.ecx.lgi.io", "port": 80},
        "XAGGET": {"host": "172.16.100.90", "port": 1337, "repo": "eos_srxx", "duration": "",
                   "elastic": "172.23.124.1", "elastic_port": "9200", "cpe": "3C36E4-EOSSTB-003356424204",
                   "test_result": "172.16.100.98"
        }
    },
    "tedh_qa_nl": {
        "CPE_FW_VERSION": "060-ap",
        # "CPE_ID": "3C36E4-EOSSTB-003674367101",
        "country": "nl",
        "default_language": "en",
        "root_id": ["omw_playmore_en"],
        "fallback_root_id": ["omw_hzn4_vod"],
        "ITFAKER": {"host": "itfaker.preprod.nl.internal", "port": 80, "env": "vodziggopreprod"},
        "VRM": {"BS": {"host": "vrm_bs_8092.preprod.nl.internal", "ports": [80]},
                "DS": {"host": "vrm_ds_8083.preprod.nl.internal", "ports": [80]},
                "BS1": {"host": "vrm_bs_8092.preprod.nl.internal", "ports": [80]},
                "BS2": {"host": "vrm_bs_8092.preprod.nl.internal", "ports": [80]}
                },
        # BLOCKED
        "SEACHANGE": {"TRAXIS_WEB": {"host": "obotraxis.preprod.nl.internal", "port": 80, "path": "traxis/web"}},
        # BLOCKED
        "MICROSERVICES": {
            "OBOQBR": "oboqbr.preprod.nl.internal"
        },
        "XAP": {"host": "xap.nl.ecx.lgi.io", "port": 80},
        "XAGGET": {"host": "172.16.100.90", "port": 1337, "repo": "eos_srxx", "duration": "",
                   "elastic": "172.23.124.1", "elastic_port": "9200", "cpe": "3C36E4-EOSSTB-003356424204",
                   "test_result": "172.16.100.98"
                   }
    }
}